#!/bin/bash

git clone https://github.com/klen/python-mode.git
git clone https://github.com/msanders/snipmate.vim.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/kien/ctrlp.vim.git
git clone git://github.com/Lokaltog/vim-powerline.git
git clone git://github.com/andrewebdev/dart-vim-plugin.git

